//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Breakr" />
    <CardContent>
      I want to be able to have AI watch a clip (whether via a URL, MP4 or .mov)
      of a sports play and identify exactly what is going on and what players
      are moving where so that coaches can then use that collected data to gain
      insights that inform their gameplan
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
