//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Clips: [
      {
        Title: 'Championship Final Play',
        URL: 'https://example.com/championship-final-play.mp4',
        Analysis:
          'In the final moments, player #23 from the Eagles makes a surprising left flank move, bypassing two defenders and scoring the winning goal.',
      },
      {
        Title: 'Underdog Victory',
        URL: 'https://example.com/underdog-victory.mp4',
        Analysis:
          'The underdog team executes a perfect counter-attack strategy, with player #11 making a critical pass that leads to a goal against the favorites.',
      },
      {
        Title: 'Defensive Masterclass',
        URL: 'https://example.com/defensive-masterclass.mp4',
        Analysis:
          "Team A's defense, especially player #5, shows exceptional skill in blocking and tackling, preventing Team B from scoring throughout the game.",
      },
      {
        Title: 'Midfield Dominance',
        URL: 'https://example.com/midfield-dominance.mp4',
        Analysis:
          "The midfielders of the Hawks, particularly player #8, control the game's pace, creating numerous opportunities and dominating possession.",
      },
      {
        Title: "Goalkeeper's Best Saves",
        URL: 'https://example.com/goalkeepers-best-saves.mp4',
        Analysis:
          "The compilation highlights the goalkeeper's agility and reflexes, showcasing top saves that kept the team in contention.",
      },
    ],
    Players: [
      { Name: 'John Doe', SharedWith: 'Team A, Team B' },
      { Name: 'Jane Smith', SharedWith: 'Team C' },
      { Name: 'Michael Brown', SharedWith: 'Team D, Team E' },
      { Name: 'Emily White', SharedWith: 'Team A, Team C' },
      { Name: 'Alex Johnson', SharedWith: 'Team B, Team D' },
    ],
    Teams: [
      { Name: 'Hawks' },
      { Name: 'Eagles' },
      { Name: 'Falcons' },
      { Name: 'Lions' },
      { Name: 'Tigers' },
    ],
  },
};
export default data;
