//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';
import grOriginal from 'ra-language-greek';

const enResources = {
  resources: {
    Clips: {
      name: 'Clips',
      fields: { Title: 'Title', URL: 'Url', Analysis: 'Analysis', id: 'id' },
    },
    Players: {
      name: 'Players',
      fields: { Name: 'Name', SharedWith: 'Shared With', id: 'id' },
    },
    Teams: { name: 'Teams', fields: { Name: 'Name', id: 'id' } },
  },
};
const frResources = {
  resources: {
    Clips: {
      name: 'Clips (fr)',
      fields: {
        Title: 'Title (fr)',
        URL: 'Url (fr)',
        Analysis: 'Analysis (fr)',
        id: 'id',
      },
    },
    Players: {
      name: 'Players (fr)',
      fields: { Name: 'Name (fr)', SharedWith: 'Shared With (fr)', id: 'id' },
    },
    Teams: { name: 'Teams (fr)', fields: { Name: 'Name (fr)', id: 'id' } },
  },
};
const grResources = {
  resources: {
    Clips: {
      name: 'Clips (gr)',
      fields: {
        Title: 'Title (gr)',
        URL: 'Url (gr)',
        Analysis: 'Analysis (gr)',
        id: 'id',
      },
    },
    Players: {
      name: 'Players (gr)',
      fields: { Name: 'Name (gr)', SharedWith: 'Shared With (gr)', id: 'id' },
    },
    Teams: { name: 'Teams (gr)', fields: { Name: 'Name (gr)', id: 'id' } },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);
const gr = mergeTranslations(grOriginal, grResources);

const translations = { en, fr, gr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
    { locale: 'gr', name: 'Ελληνικά' },
  ],
);
